name: Triggered Workflow

on:
  repository_dispatch:
    types: [trigger-event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repoA
        uses: actions/checkout@v2

      - name: Print Event Payload
        run: |
          echo "Event payload: ${{ toJson(github.event.client_payload) }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/scripts/requirements.txt

      - name: Run Python script
        env:
          MY_TOKEN: ${{ secrets.MY_SECRET }}
        run: |
          python .github/workflows/scripts/main.py ${{ github.event.client_payload.version_tag }}
